Refactoring PR
dapariciom/ShortURLProject pull request #4
Opened 2022-08-24 18:23 UTC by dapariciom

2022-08-25 09:41 UTC, BeeAM17 commented on src/main/java/com/example/demo/HeartBeatController.java
> +        return new ResponseEntity<String>(msg,headers, HttpStatus.OK);
You don't need String here, just use `return new ResponseEntity<>(msg, headers, HttpStatus.OK);`
And don't forget for space before headers

2022-08-25 09:41 UTC, BeeAM17 commented on src/main/java/com/example/demo/ShortenUrlController.java
> +            return new ResponseEntity<UrlResponse>(urlResponse, HttpStatus.OK);
Same here, no need to use `UrlResponse`, just remove it

2022-08-25 09:41 UTC, BeeAM17 commented on src/main/java/com/example/demo/ShortenUrlController.java
> +        return new ResponseEntity<UrlResponse>(urlResponse, HttpStatus.BAD_REQUEST);
Same here

2022-08-25 18:45 UTC, dapariciom commented on src/main/java/com/example/demo/HeartBeatController.java
> +        return new ResponseEntity<String>(msg,headers, HttpStatus.OK);
Done

2022-08-25 18:46 UTC, dapariciom commented on src/main/java/com/example/demo/ShortenUrlController.java
> +            return new ResponseEntity<UrlResponse>(urlResponse, HttpStatus.OK);
Done

2022-08-25 19:22 UTC, dapariciom commented on src/main/java/com/example/demo/ShortenUrlController.java
> +        return new ResponseEntity<UrlResponse>(urlResponse, HttpStatus.BAD_REQUEST);
Done

2022-08-26 09:06 UTC, BeeAM17 requested changes
Looks better, but let's continue our work :)

2022-08-26 09:06 UTC, BeeAM17 commented on src/main/java/com/example/shorturl/controller/HeartBeatController.java
> +        return new ResponseEntity<>("UP",headers, HttpStatus.OK);
Space is missing :)

2022-08-26 09:06 UTC, BeeAM17 commented on src/main/java/com/example/shorturl/model/UrlEntity.java
> +    private int id;
As I said, let's have long instead of int

2022-08-26 09:06 UTC, BeeAM17 commented on src/main/java/com/example/shorturl/model/UrlRequest.java
> +import lombok.*;
Avoid using wildcards

2022-08-26 09:06 UTC, BeeAM17 commented on src/main/java/com/example/shorturl/service/IShortenUrlService.java
> +    Optional<UrlEntity> shortUrl(UrlRequest urlRequest);
Add java doc please

2022-08-26 09:06 UTC, BeeAM17 commented on src/main/java/com/example/shorturl/service/sequence/ISequenceGeneratorService.java
> +    int getSequenceNumber(String sequenceName);
Should be long

2022-08-26 09:06 UTC, BeeAM17 commented on src/main/resources/application.yml
> +  port: 8080
No need to use port, if we have 8080 by default

2022-08-29 16:43 UTC, dapariciom commented on src/main/java/com/example/shorturl/controller/HeartBeatController.java
> +        return new ResponseEntity<>("UP",headers, HttpStatus.OK);
Done

2022-08-29 16:44 UTC, dapariciom commented on src/main/java/com/example/shorturl/model/UrlEntity.java
> +    private int id;
Fixed

2022-08-29 16:51 UTC, dapariciom commented on src/main/java/com/example/shorturl/model/UrlRequest.java
> +import lombok.*;
Fixed

2022-08-29 16:54 UTC, dapariciom commented on src/main/resources/application.yml
> +  port: 8080
Done

2022-08-29 16:55 UTC, dapariciom commented on src/main/java/com/example/shorturl/service/sequence/ISequenceGeneratorService.java
> +    int getSequenceNumber(String sequenceName);
Fixed

2022-08-29 17:51 UTC, dapariciom commented on src/main/java/com/example/shorturl/service/IShortenUrlService.java
> +    Optional<UrlEntity> shortUrl(UrlRequest urlRequest);
Added

2022-08-29 18:01 UTC, BeeAM17 approved these changes
Looks much better :)

2022-08-30 03:42 UTC, merged